version: '3.8'
services:
  app:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - RUN_MIGRATIONS
      - RUN_DEV_SEEDS
    depends_on:
      - postgres
    command: /bin/sh -c "chmod +x ./startup.sh && sh /app/startup.sh"
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: